name: Configure Dev Dependencies

runs:
  using: "composite"
  steps:
    - uses: "./.github/actions/setup-build-dependencies/macos.yml"
      if: startsWith(matrix.os, 'macos')
    - uses: "./.github/actions/setup-build-dependencies/ubuntu.yml"
      if: startsWith(matrix.os, 'ubuntu')
    - uses: "./.github/actions/setup-build-dependencies/windows.yml"
      if: startsWith(matrix.os, 'windows')
