name: Configure Dev Dependencies

runs:
  using: "composite"
  steps:
    - uses: "./macos.yml"
      if: startsWith(matrix.os, 'macos')
    - uses: "./ubuntu.yml"
      if: startsWith(matrix.os, 'ubuntu')
    - uses: "./windows.yml"
      if: startsWith(matrix.os, 'windows')
