name: Configure macOS Dependencies

runs:
  steps:
    - name: Install brew dependencies
      run: brew install python3 ruby openjdk node php lmdb mcpp
    - name: Install test dependencies
      run: python3 -m pip install passlib cryptography
