name: "Build PIP Packages"

on:
  workflow_call: # Allows calling from other workflows
  workflow_dispatch: # Allows manual triggering

jobs:
  build-python-packages:

    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Install Build Dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install build

      - name: Build PIP Package
        working-directory: python
        run: python3 -m build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pip-packages-${{ matrix.os }}
          path: |
            python/dist/zeroc_ice-*.whl
            python/dist/zeroc_ice-*.tar.gz
