name: ci

on:
  workflow_dispatch:
  push:
    branches: ["3.7", "main", "macos-windows-ci"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["3.7", "main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: ${{ matrix.language }} / ${{ matrix.os }}
    strategy:
      matrix:
        languages: [[cpp], [csharp], [java], [python], [js]] # languages available on all os
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
          - os: macos-latest
            languages: swift
          - os: macos-latest
            languages: [php, ruby]
          - os: ubuntu-latest
            languages: [php, ruby]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          key: ${{ runner.os }}-build
        if: startsWith(matrix.os, 'ubuntu') || startsWith(matrix.os, 'macos')

      - name: Window Cache
        if: startsWith(matrix.os, 'windows')
        uses: actions/cache@v3
        with:
          path: |
            **/bin
            **/obj
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-${{ github.sha }}
            ${{ runner.os }}-build-

      - name: Build ${{ join(matrix.languages, ',') }} on ${{ matrix.os }}
        uses: ./.github/actions/build
        with:
          languages: ${{ matrix.languages }}

      - name: Test ${{ join(matrix.languages, ',') }} on ${{ matrix.os }}
        uses: ./.github/actions/test
        with:
          languages: ${{ matrix.languages }}
