name: ci

on:
  workflow_dispatch:
  push:
    branches: ["3.7", "main", "macos-windows-ci"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["3.7", "main"]
  schedule:
    - cron: "34 18 * * 3"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  # linux-self-hosted:
  #   runs-on: [self-hosted, linux]
  #   steps:
  #     - name: Checkout repository
  #       uses: actions/checkout@v3
  #     - name: Build
  #       run: make -j8 V=1
  #     - name: Test
  #       run: ./allTests.py --workers=4

  linux-latest:
    runs-on: [ubuntu-latest]
    steps:
      - name: Install dependencies
        run: sudo apt-get install -y python3 python3-pip ruby openjdk-8-jdk nodejs php-cli liblmdb-dev libmcpp-dev libreadline-dev libssl-dev
      - name: Install test dependencies
        run: python3 -m pip install passlib cryptography
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
      - name: Build
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          make -j3 V=1
      - name: Test
        run: ./allTests.py --workers=3

  macos-latest:
    runs-on: [macos-latest]
    steps:
      - name: Install brew dependencies
        run: brew install python3 ruby openjdk node php lmdb mcpp
      - name: Install test dependencies
        run: python3 -m pip install passlib cryptography
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
      - name: Build
        run: |
          export PATH="/usr/lib/ccache:/usr/local/opt/ccache/libexec:$PATH"
          make -j3 V=1
      - name: Test
        run: ./allTests.py --workers=3

  windows-latest:
    runs-on: [windows-latest]
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            **/bin
            **/obj
          key: ${{ runner.os }}-build-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-build-
      - name: Build
        run: msbuild /m cpp\msbuild\ice.proj
      # - name: Test
      #   run: ./allTests.py --workers=3
