name: ci

on:
  workflow_dispatch:
  push:
    branches: ["3.7", "main", "macos-windows-ci"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["3.7", "main"]
  schedule:
    - cron: "34 18 * * 3"

jobs:
  linux-latest:
    runs-on: [self-hosted, linux]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build
        run: make -j8 V=1
      - name: Test
        run: ./allTests.py --workers=4

  macos-latest:
    runs-on: [macos-latest]
    steps:
      - name: Install brew dependencies
        run: brew install python3 ruby openjdk node php lmdb mcpp
      - name: Install test dependencies
        run: python3 -m pip install passlib cryptography
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build
        run: make -j3 V=1
      - name: Test
        run: ./allTests.py --workers=3

  windows-latest:
    runs-on: [windows-latest]
    steps:
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.1
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Build
        run: msbuild /m cpp\msbuild\ice.proj
      # - name: Test
      #   run: ./allTests.py --workers=3
