name: Generate documentation

on:
  workflow_dispatch:
  push:
    branches: ["main", "publish-api-reference"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]

jobs:
  ci:
    name: Build Doxygen documentation

    runs-on: macos-14
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Dependencies
        uses: ./.github/actions/setup-dependencies

      - name: Install awscli
        run: brew install awscli || true

      - name: Install doxygen and graphviz (a dependency of Doxygen for generating diagrams)
        run: brew install doxygen graphviz || true

      - name: Generate Doxygen Documentation for Slice
        working-directory: ./doxygen
        run: doxygen

      - name: Generate Doxygen Documentation for C++
        working-directory: ./cpp
        run: |
          make generate-srcs
          cd doxygen
          doxygen

      - name: Sync Documentation to S3
        run: |
          aws s3 sync ./cpp/doxygen/cpp s3://zeroc-ice-docs/api/ice/main/cpp --delete
          aws s3 cp ./cpp/doxygen/icecpp.tag s3://zeroc-ice-docs/api/ice/main/icecpp.tag

          aws s3 sync ./cpp/doxygen/slice s3://zeroc-ice-docs/api/ice/main/slice --delete
          aws s3 cp ./cpp/doxygen/slice.tag s3://zeroc-ice-docs/api/ice/main/slice.tag
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
        # if: github.ref == 'refs/heads/main'
