name: Swift Format

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]

jobs:
  swift-format:
    name: Swift format and lint
    runs-on: ubuntu-latest
    container:
      image: swift
      volumes:
        - ${{ github.workspace }}:${{ github.workspace }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set safe directory
        run: |
          git config --global --add safe.directory /__w/ice/ice

      - name: swift-format Format
        working-directory: swift
        run: |
          swift format . --recursive --in-place --configuration .swift-format.json
          git diff --exit-code

      - name: swift-format Lint
        working-directory: swift
        run: swift format lint . --recursive --strict --configuration .swift-format.json
