name: Swift lint and format

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths:
      - "swift/**"
  pull_request:
    # The branches below must be a subset of the branches above
    branches: ["main"]
    paths:
      - "swift/**"

jobs:
  swift-format:
    name: Swift Format & Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: swift-actions/setup-swift@v2

      - name: swift-format Format
        working-directory: swift
        run: swift format . --recursive --configuration .swift-format.json

      - name: swift-format Lint
        working-directory: swift
        run: swift format lint . --recursive --strict --configuration .swift-format.json
